export const TINYMCE_VERSION = '8.8.2';

export const TINYMCE_VENDOR_ASSETS = Object.freeze([
  'tinymce.min.js',
  'license.md',
  'notices.txt',
  'themes/silver/theme.min.js',
  'models/dom/model.min.js',
  'plugins/lists/plugin.min.js',
  'plugins/link/plugin.min.js',
  'plugins/image/plugin.min.js',
  'plugins/table/plugin.min.js',
  'plugins/charmap/plugin.min.js',
  'plugins/emoticons/plugin.min.js',
  'plugins/emoticons/js/emojis.min.js',
  'plugins/insertdatetime/plugin.min.js',
  'skins/ui/oxide/skin.min.css',
  'skins/ui/oxide/content.min.css',
  'skins/content/default/content.min.css',
  'skins/ui/oxide-dark/skin.min.css',
  'skins/ui/oxide-dark/content.min.css',
  'skins/content/dark/content.min.css',
]);

export const CUSTOM_ICON_PACK = 'phphtmledit';
export const CUSTOM_ICON_ASSET = `icons/${CUSTOM_ICON_PACK}/icons.min.js`;
export const CUSTOM_ICON_MODIFIED_DATE = '2026-08-13';

// Pinned to TinyMCE 8.8.2. This intentionally covers the configured toolbar,
// the Silver shell, and the link/image/table/charmap/emoticons/insertdatetime UI.
export const CUSTOM_ICON_NAMES = Object.freeze([
  'align-center',
  'align-justify',
  'align-left',
  'align-right',
  'bold',
  'checkmark',
  'chevron-down',
  'chevron-right',
  'close',
  'color-picker',
  'color-swatch-remove-color',
  'copy',
  'cut',
  'cut-column',
  'cut-row',
  'duplicate-column',
  'duplicate-row',
  'emoji',
  'highlight-bg-color',
  'horizontal-rule',
  'image',
  'indent',
  'insert-character',
  'insert-time',
  'italic',
  'link',
  'lock',
  'more-drawer',
  'new-document',
  'new-tab',
  'ordered-list',
  'outdent',
  'paste',
  'paste-column-after',
  'paste-column-before',
  'paste-row-after',
  'paste-row-before',
  'paste-text',
  'print',
  'redo',
  'remove-formatting',
  'resize-handle',
  'select-all',
  'selected',
  'sourcecode',
  'strike-through',
  'subscript',
  'superscript',
  'table',
  'table-cell-properties',
  'table-delete-column',
  'table-delete-row',
  'table-delete-table',
  'table-insert-column-after',
  'table-insert-column-before',
  'table-insert-row-above',
  'table-insert-row-after',
  'table-merge-cells',
  'table-row-properties',
  'table-split-cells',
  // Deliberately omit Silver's fallback SVG. A missing required icon then
  // renders the detectable `!not found!` marker during visual verification.
  'text-color',
  'underline',
  'undo',
  'unlink',
  'unlock',
  'unordered-list',
  'unselected',
  'warning',
]);

export const TINYMCE_ASSETS = Object.freeze([
  ...TINYMCE_VENDOR_ASSETS,
  CUSTOM_ICON_ASSET,
]);
